// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU3iYQNEqmHyT7tMk4oC12Qi0k26xMRyU',
    appId: '1:314403589372:web:25af65ff7994fdb9db1b79',
    messagingSenderId: '314403589372',
    projectId: 'cantinhodoespeto-5c8e3',
    authDomain: 'cantinhodoespeto-5c8e3.firebaseapp.com',
    storageBucket: 'cantinhodoespeto-5c8e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdD4vlHNQPppIK8ZyuGWLnC1KKbjGGqQ8',
    appId: '1:314403589372:android:02c915a7359a6b4fdb1b79',
    messagingSenderId: '314403589372',
    projectId: 'cantinhodoespeto-5c8e3',
    storageBucket: 'cantinhodoespeto-5c8e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-EAM6hFTFw5n9v3gY4tio5JzCMX-ajo',
    appId: '1:314403589372:ios:deb235e39d0c6d15db1b79',
    messagingSenderId: '314403589372',
    projectId: 'cantinhodoespeto-5c8e3',
    storageBucket: 'cantinhodoespeto-5c8e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationPraticas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-EAM6hFTFw5n9v3gY4tio5JzCMX-ajo',
    appId: '1:314403589372:ios:deb235e39d0c6d15db1b79',
    messagingSenderId: '314403589372',
    projectId: 'cantinhodoespeto-5c8e3',
    storageBucket: 'cantinhodoespeto-5c8e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationPraticas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU3iYQNEqmHyT7tMk4oC12Qi0k26xMRyU',
    appId: '1:314403589372:web:607fbaf95e0c6e11db1b79',
    messagingSenderId: '314403589372',
    projectId: 'cantinhodoespeto-5c8e3',
    authDomain: 'cantinhodoespeto-5c8e3.firebaseapp.com',
    storageBucket: 'cantinhodoespeto-5c8e3.firebasestorage.app',
  );

}