name: flutter_application_praticas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_auth_web: ^5.13.6
  intl: ^0.19.0
  dropdown_search: ^6.0.1
  google_fonts: ^5.0.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.18
  brasil_fields: ^1.15.0
  js: ^0.6.3
  cloud_firestore: ^5.6.1
  currency_text_input_formatter: ^2.1.7
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon/logoCDE.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png