name: flutter_application_praticas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_auth_web: ^5.13.7
  intl: 0.20.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.0.18
  brasil_fields: ^1.15.0
  js: ^0.6.3
  cloud_firestore: ^5.6.2
  currency_text_input_formatter: ^2.1.7
  flutter_pos_printer_platform_image_3: ^1.2.4
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon/logoCDE.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png