name: flutter_application_praticas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_auth: ^4.16.0
  cloud_firestore: any
  intl: ^0.19.0
  dropdown_search: ^6.0.1
  google_fonts: ^5.0.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.18
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
